include(CheckCXXCompilerFlag)
check_cxx_compiler_flag("-fsycl" STRATA_COMPILER_HAS_FSYCL)
if(NOT STRATA_COMPILER_HAS_FSYCL)
  message(FATAL_ERROR "SYCL requires a SYCL compiler; configure with -DCMAKE_CXX_COMPILER=icpx")
endif()

add_library(strata_sycl_runtime STATIC src/sycl/runtime.cpp)
target_include_directories(strata_sycl_runtime PUBLIC ${PROJECT_SOURCE_DIR}/include)
target_compile_options(strata_sycl_runtime PUBLIC -fsycl)
target_link_options(strata_sycl_runtime PUBLIC -fsycl)
target_link_libraries(strata_sycl_runtime PRIVATE strata_warnings)
target_compile_definitions(strata_sycl_runtime PUBLIC STRATA_ENABLE_SYCL=1)

add_library(strata_core STATIC src/sycl/device.cpp)
target_link_libraries(strata_core PUBLIC strata_sycl_runtime strata_plan)
add_executable(strata-device src/core/device_main.cpp)
target_link_libraries(strata-device PRIVATE strata_core)

add_library(strata_kernels STATIC src/kernels/sycl/elementwise.cpp src/kernels/sycl/router.cpp
                                 src/kernels/sycl/native_router.cpp src/kernels/sycl/gdn.cpp
                                 src/kernels/sycl/quantize_act.cpp src/kernels/sycl/bf16_gemv.cpp
                                 src/kernels/sycl/native_mmvq.cpp)
target_link_libraries(strata_kernels PUBLIC strata_core strata_artifact)
target_compile_options(strata_kernels PRIVATE -ffp-contract=off)

option(STRATA_SYCL_TESTS "Build GPU parity and runtime tests for SYCL" ON)
if(STRATA_SYCL_TESTS)
  enable_testing()
  add_executable(sycl_runtime_test tests/sycl/runtime.cpp)
  target_link_libraries(sycl_runtime_test PRIVATE strata_sycl_runtime)
  add_test(NAME sycl_runtime COMMAND sycl_runtime_test)
  set_tests_properties(sycl_runtime PROPERTIES TIMEOUT 60)
  add_test(NAME sycl_device COMMAND strata-device --selftest)
  set_tests_properties(sycl_device PROPERTIES TIMEOUT 60)
  add_executable(sycl_kernels_test tests/sycl/kernels.cpp)
  target_link_libraries(sycl_kernels_test PRIVATE strata_kernels)
  target_compile_options(sycl_kernels_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_kernels COMMAND sycl_kernels_test)
  set_tests_properties(sycl_kernels PROPERTIES TIMEOUT 90)
  add_executable(sycl_gdn_test tests/sycl/gdn.cpp)
  target_link_libraries(sycl_gdn_test PRIVATE strata_kernels)
  target_compile_options(sycl_gdn_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_gdn COMMAND sycl_gdn_test)
  set_tests_properties(sycl_gdn PROPERTIES TIMEOUT 90)
  add_executable(sycl_quantize_test tests/sycl/quantize.cpp)
  target_link_libraries(sycl_quantize_test PRIVATE strata_kernels)
  target_compile_options(sycl_quantize_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_quantize COMMAND sycl_quantize_test)
  set_tests_properties(sycl_quantize PROPERTIES TIMEOUT 90)
  add_executable(sycl_bf16_test tests/sycl/bf16.cpp)
  target_link_libraries(sycl_bf16_test PRIVATE strata_kernels)
  target_compile_options(sycl_bf16_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_bf16 COMMAND sycl_bf16_test)
  set_tests_properties(sycl_bf16 PROPERTIES TIMEOUT 90)
  add_executable(sycl_mmvq_test tests/sycl/mmvq.cpp)
  target_link_libraries(sycl_mmvq_test PRIVATE strata_kernels)
  target_compile_options(sycl_mmvq_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_mmvq COMMAND sycl_mmvq_test)
  set_tests_properties(sycl_mmvq PROPERTIES TIMEOUT 90)
endif()
