include(CheckCXXCompilerFlag)
check_cxx_compiler_flag("-fsycl" STRATA_COMPILER_HAS_FSYCL)
if(NOT STRATA_COMPILER_HAS_FSYCL)
  message(FATAL_ERROR "SYCL requires a SYCL compiler; configure with -DCMAKE_CXX_COMPILER=icpx")
endif()

add_library(strata_sycl_runtime STATIC src/sycl/runtime.cpp)
target_include_directories(strata_sycl_runtime PUBLIC ${PROJECT_SOURCE_DIR}/include)
target_compile_options(strata_sycl_runtime PUBLIC -fsycl)
target_link_options(strata_sycl_runtime PUBLIC -fsycl)
target_link_libraries(strata_sycl_runtime PRIVATE strata_warnings)
target_compile_definitions(strata_sycl_runtime PUBLIC STRATA_ENABLE_SYCL=1)

add_library(strata_core STATIC src/sycl/device.cpp)
target_link_libraries(strata_core PUBLIC strata_sycl_runtime strata_plan)
add_executable(strata-device src/core/device_main.cpp)
target_link_libraries(strata-device PRIVATE strata_core)

add_library(strata_kernels STATIC src/kernels/sycl/elementwise.cpp src/kernels/sycl/router.cpp
                                 src/kernels/sycl/native_router.cpp src/kernels/sycl/gdn.cpp
                                 src/kernels/sycl/quantize_act.cpp src/kernels/sycl/bf16_gemv.cpp
                                 src/kernels/sycl/native_mmvq.cpp src/kernels/sycl/gr.cpp
                                 src/kernels/sycl/rope.cpp src/kernels/sycl/kv.cpp
                                 src/kernels/sycl/attention.cpp src/kernels/sycl/qsa_index.cpp
                                 src/kernels/sycl/native_qsa_indexer.cpp src/kernels/sycl/qsa_select.cpp
                                 src/kernels/sycl/decode_attention.cpp src/kernels/sycl/kv_stream.cpp
                                 src/kernels/sycl/ple.cpp src/kernels/sycl/s2_gemv_q8.cpp src/kernels/sycl/s_gemv.cpp src/kernels/sycl/shared_expert.cpp)
target_link_libraries(strata_kernels PUBLIC strata_core strata_artifact)
target_compile_options(strata_kernels PRIVATE -ffp-contract=off)
set_source_files_properties(src/kernels/sycl/rope.cpp src/kernels/sycl/native_qsa_indexer.cpp src/kernels/sycl/ple.cpp PROPERTIES COMPILE_OPTIONS "-fno-fast-math")

option(STRATA_SYCL_TESTS "Build GPU parity and runtime tests for SYCL" ON)
if(STRATA_SYCL_TESTS)
  enable_testing()
  add_executable(sycl_runtime_test tests/sycl/runtime.cpp)
  target_link_libraries(sycl_runtime_test PRIVATE strata_sycl_runtime)
  add_test(NAME sycl_runtime COMMAND sycl_runtime_test)
  set_tests_properties(sycl_runtime PROPERTIES TIMEOUT 60)
  add_test(NAME sycl_device COMMAND strata-device --selftest)
  set_tests_properties(sycl_device PROPERTIES TIMEOUT 60)
  add_executable(sycl_kernels_test tests/sycl/kernels.cpp)
  target_link_libraries(sycl_kernels_test PRIVATE strata_kernels)
  target_compile_options(sycl_kernels_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_kernels COMMAND sycl_kernels_test)
  set_tests_properties(sycl_kernels PROPERTIES TIMEOUT 90)
  add_executable(sycl_gdn_test tests/sycl/gdn.cpp)
  target_link_libraries(sycl_gdn_test PRIVATE strata_kernels)
  target_compile_options(sycl_gdn_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_gdn COMMAND sycl_gdn_test)
  set_tests_properties(sycl_gdn PROPERTIES TIMEOUT 90)
  add_executable(sycl_quantize_test tests/sycl/quantize.cpp)
  target_link_libraries(sycl_quantize_test PRIVATE strata_kernels)
  target_compile_options(sycl_quantize_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_quantize COMMAND sycl_quantize_test)
  set_tests_properties(sycl_quantize PROPERTIES TIMEOUT 90)
  add_executable(sycl_bf16_test tests/sycl/bf16.cpp)
  target_link_libraries(sycl_bf16_test PRIVATE strata_kernels)
  target_compile_options(sycl_bf16_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_bf16 COMMAND sycl_bf16_test)
  set_tests_properties(sycl_bf16 PROPERTIES TIMEOUT 90)
  add_executable(sycl_mmvq_test tests/sycl/mmvq.cpp)
  target_link_libraries(sycl_mmvq_test PRIVATE strata_kernels)
  target_compile_options(sycl_mmvq_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_mmvq COMMAND sycl_mmvq_test)
  set_tests_properties(sycl_mmvq PROPERTIES TIMEOUT 90)
  add_executable(sycl_gr_test tests/sycl/gr.cpp)
  target_link_libraries(sycl_gr_test PRIVATE strata_kernels)
  target_compile_options(sycl_gr_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_gr COMMAND sycl_gr_test)
  set_tests_properties(sycl_gr PROPERTIES TIMEOUT 90)
  add_executable(sycl_rope_test tests/sycl/rope.cpp)
  target_link_libraries(sycl_rope_test PRIVATE strata_kernels)
  target_compile_options(sycl_rope_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_rope COMMAND sycl_rope_test)
  add_test(NAME sycl_rope_table COMMAND sycl_rope_test --table)
  set_tests_properties(sycl_rope sycl_rope_table PROPERTIES TIMEOUT 90)
  add_executable(sycl_kv_test tests/sycl/kv.cpp)
  target_link_libraries(sycl_kv_test PRIVATE strata_kernels)
  target_compile_options(sycl_kv_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_kv COMMAND sycl_kv_test)
  set_tests_properties(sycl_kv PROPERTIES TIMEOUT 90)
  add_executable(sycl_attention_test tests/sycl/attention.cpp)
  target_link_libraries(sycl_attention_test PRIVATE strata_kernels)
  target_compile_options(sycl_attention_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_attention COMMAND sycl_attention_test)
  set_tests_properties(sycl_attention PROPERTIES TIMEOUT 90)
  add_executable(sycl_qsa_index_test tests/sycl/qsa_index.cpp)
  target_link_libraries(sycl_qsa_index_test PRIVATE strata_kernels)
  target_compile_options(sycl_qsa_index_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_qsa_index COMMAND sycl_qsa_index_test)
  set_tests_properties(sycl_qsa_index PROPERTIES TIMEOUT 90)
  add_executable(sycl_decode_attention_test tests/sycl/decode_attention.cpp)
  target_link_libraries(sycl_decode_attention_test PRIVATE strata_kernels)
  target_compile_options(sycl_decode_attention_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_decode_attention COMMAND sycl_decode_attention_test)
  set_tests_properties(sycl_decode_attention PROPERTIES TIMEOUT 90)
  add_executable(sycl_ple_test tests/sycl/ple.cpp)
  target_link_libraries(sycl_ple_test PRIVATE strata_kernels)
  target_compile_options(sycl_ple_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_ple COMMAND sycl_ple_test)
  set_tests_properties(sycl_ple PROPERTIES TIMEOUT 90)
  add_executable(sycl_moe_test tests/sycl/moe.cpp)
  target_link_libraries(sycl_moe_test PRIVATE strata_kernels)
  target_compile_options(sycl_moe_test PRIVATE -fno-fast-math -ffp-contract=off)
  add_test(NAME sycl_moe COMMAND sycl_moe_test)
  set_tests_properties(sycl_moe PROPERTIES TIMEOUT 90)
endif()
